services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - database:/var/www/mysql
    networks:
      - inception
    expose:
      - "3306"
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  database:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ppuivif/data/mariadb

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ppuivif/data/wordpress